# Example of a scheduled job that commits new data file

name: test

# Schedule a job
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 1 * * *'
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: install packages
        run: |
          sudo apt-get -q update
          sudo apt-get install python3-bs4
          sudo apt-get install python3-requests
          sudo apt-get install xmltv-util

      - name: run
        run: |
          echo '<?xml version="1.0" encoding="UTF-8" ?>' > test.xml
          python test.py >> test.xml

      - name: commit 
        run: |
          git add test.xml
          git commit -m "new data from scheduled job"
          git log --name-only
          git status
          
